- name: variables from play level 
  hosts: localhost 
  
  tasks:
  - name: check variables 
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Trainer is {{trainer}}, duration is {{duration}}"

#this playbook search for variables in inventory file