- name: loops
  hosts: localhost 
  tasks:
  - name: print persons 
    ansible.builtin.package:
      name: "{{item}}" # item is a defaut keyword
      state: present
    loop:
    - git
    - mysql
    - postfix
    